### ISSUE TITLE
No funciona 

### ISSUE THREAD

**Issue by Yisus7u7** [Darkmux/Metasploit#1]
Bro, Metasploit esta escrito bajo ruby 2.7.2, los repositorios de termux actualizaron la versión de ruby a 3.0.0, por lo tanto Metasploit no es compatible con la versión de ruby de termux, y todos los scripts de instalar Metasploit actualmente no funcionan, toca es esperar que actualize Metasploit a la versión de ruby 3.0.0 o que suceda un milagro, buen día

**Comment by ricklble** [comment]
gracias bro creía que algo andaba mal con mi termux👍🏻

**Comment by Yisus7u7** [comment]
Ya el error lo e solucionado, funciona perfecto en  todas las arquitecturas, la única con la que tiene problemas es arch64, aquí esta mi repo : 
https://github.com/Yisus7u7/Metasploit_by-yisus

**Comment by ricklble** [comment]
bien probaré a ver si me funciona gracias

**Comment by ricklble** [comment]
si en aarch64 tiene problemas, ya hize todos los pasos y me da el error de que "ruby.deb" no es un archivo deb

**Comment by Yisus7u7** [comment]
Si me an dicho, a todos les sirve pero a los de arch64 no, entonces si quieres Metasploit deberás instalar una distro por chroot, ya sea kali a parrot
